version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.laravel
        container_name: laravel
        ports:
            - "80:80"
        depends_on:
            - db
    db:
        image: mysql:8.0
        container_name: db_laravel
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
    next:
        build:
            context: .
            dockerfile: Dockerfile.next
        container_name: next
        ports:
            - "3000:3000"
        depends_on:
            - db
            - app
volumes:
    db_data:
